#ifndef KEYWORD_H
#define KEYWORD_H

#define CREATE_KEYWORD "CREATE"
#define DATABASE_KEYWORD "DATABASE"
#define TABLE_KEYWORD "TABLE"
#define VARCHAR_KEYWORD "VARCHAR"
#define TEXT_KEYWORD "TEXT"
#define INT_KEYWORD "INT"
#define INT_KEYWORD "INT"
#define INT_KEYWORD "INT"
#define NOT_KEYWORD "NOT"
#define NULL_KEYWORD "NULL"
#define NOT_NULL_KEYWORD "NOT NULL"
#define PRIMARY_KEYWORD "PRIMARY"
#define KEY_KEYWORD "KEY"
#define PRIMARY_KEY_KEYWORD "PRIMARY KEY"
#define AUTO_INCREMENT_KEYWORD "AUTO_INCREMENT"

#define SQL_KEYWORDS { \
    CREATE_KEYWORD, DATABASE_KEYWORD, TABLE_KEYWORD, VARCHAR_KEYWORD, \
    TEXT_KEYWORD, INT_KEYWORD, NOT_KEYWORD, NULL_KEYWORD, \
    PRIMARY_KEYWORD, KEY_KEYWORD, AUTO_INCREMENT_KEYWORD \
}

#define SQL_CONSTRAINTS { \
    PRIMARY_KEYWORD, KEY_KEYWORD, AUTO_INCREMENT_KEYWORD, \
    NOT_KEYWORD, NULL_KEYWORD, NOT_NULL_KEYWORD, PRIMARY_KEY_KEYWORD \
}

#endif //KEYWORD_H
